base.folder=/Users/calvi/Downloads
move.limit=-1

rule.count=6

rule.1.extensions=
rule.1.keyword=resume
rule.1.olderThanDays=
rule.1.destination=Resumes

rule.2.extensions=jpg,jpeg,png
rule.2.keyword=screenshot
rule.2.olderThanDays=
rule.2.destination=Screenshots

rule.3.extensions=java,py,js,ts,html,css,sql,c,cpp,h,hpp,r
rule.3.keyword=
rule.3.olderThanDays=
rule.3.destination=Code

rule.4.extensions=xlsx,csv
rule.4.keyword=
rule.4.olderThanDays=
rule.4.destination=Sheets

rule.5.extensions=jpg,jpeg,png
rule.5.keyword=
rule.5.olderThanDays=
rule.5.destination=Pictures

rule.6.extensions=
rule.6.keyword=
rule.6.olderThanDays=730
rule.6.destination=Old